# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trans < Formula
  desc ""
  homepage ""
  version "0.1.4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "http://github.com/yulintan/trans/releases/download/v0.1.4/trans_0.1.4_Darwin_x86_64.tar.gz"
    sha256 "b73693fc967a260151192bfb2c414f613be5613c32ce2b0a715df7072418fde9"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "http://github.com/yulintan/trans/releases/download/v0.1.4/trans_0.1.4_Darwin_arm64.tar.gz"
    sha256 "b711ab94f9c78060c02714be8436a137f8a231ffceef360ec9c8966a2f0beb3c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "http://github.com/yulintan/trans/releases/download/v0.1.4/trans_0.1.4_Linux_x86_64.tar.gz"
    sha256 "cb69f621ce399dc1fba45a66a359e774125424b1b471869028b533e8f541aebd"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "http://github.com/yulintan/trans/releases/download/v0.1.4/trans_0.1.4_Linux_arm64.tar.gz"
    sha256 "60cd7da2c1317b8c87fe7fd21d22d8b1f50db585ff03dbb8ec77ca62e510ceb2"
  end

  depends_on "git"
  depends_on "zsh" => :optional

  conflicts_with "svn"
  conflicts_with "bash"

  def install
    bin.install "trans"
  end
end
