# This file was generated by GoReleaser. DO NOT EDIT.
class Translate < Formula
  desc "CLI to translate words between languages"
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/yulintan/translate/releases/download/v0.1.0/translate_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "d7e63bc51992884199569276dae27f4d28eb4a48d080c959a0e399e0c46c958f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/yulintan/translate/releases/download/v0.1.0/translate_0.1.0_Linux_x86_64.tar.gz"
      sha256 "f488fc282b01ed74485ed1b0f24b376d1a7efd1e20f3e23f15a72ad81c98dadb"
    end
  end

  def install
    bin.install "translate"
  end
end
